CREATE DATABASE IF NOT EXISTS scb;
USE scb;

CREATE TABLE IF NOT EXISTS admins(
  userId CHAR(8) PRIMARY KEY,
  passHash CHAR(97) NOT NULL,
  type TINYINT NOT NULL
);

INSERT IGNORE INTO admins VALUES
(
  '00bankai',
  '$argon2id$v=19$m=65536,t=3,p=4$gsvk4X+0pHCGpbKdyEEOwQ$Nn4Ou/DFPKbJMZ/ibG6T+PxZ1LDpdZCQ8oeJJrXd4EE',
  TRUE
),
(
  '01bankai',
  '$argon2id$v=19$m=65536,t=3,p=4$7HNqYEOoT6/Rh/C7mFWbqQ$lpq7qPjji91hINkcmYvXT16lcruPrCASJ4fk2houXmo',
  FALSE
);

CREATE TABLE IF NOT EXISTS passkeys (
  id VARCHAR(64) PRIMARY KEY,
  publicKey VARBINARY(512) NOT NULL,
  userId CHAR(8) NOT NULL,
  webAuthnId VARBINARY(64) NOT NULL,
  counter BIGINT NOT NULL,
  FOREIGN KEY (userId) REFERENCES admins(userId) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users(
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  devId VARCHAR(36) NOT NULL,
  name VARCHAR(30) NOT NULL,
  mobNoEn VARBINARY(44) NOT NULL,
  mobNoHs VARBINARY(32) NOT NULL,
  type SMALLINT DEFAULT 0
);

CREATE INDEX idx_users_mob_hash ON users(mobNoHs);

CREATE TABLE IF NOT EXISTS blocks(
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  mobNoEn VARBINARY(44) NOT NULL,
  mobNoHs VARBINARY(32) NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,
  type SMALLINT DEFAULT 0
);

CREATE INDEX idx_blocks_mob_hash ON blocks(mobNoHs);

CREATE TABLE IF NOT EXISTS codes(
  code VARCHAR(8) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS apps(
  code VARCHAR(8) PRIMARY KEY
);
