CREATE DATABASE IF NOT EXISTS scb;

USE scb;

CREATE TABLE IF NOT EXISTS admins(
  userId CHAR(8) PRIMARY KEY,
  passHash CHAR(97) NOT NULL
);

INSERT IGNORE INTO admins VALUE(
  '00bankai',
  '$argon2id$v=19$m=65536,t=3,p=4$gsvk4X+0pHCGpbKdyEEOwQ$Nn4Ou/DFPKbJMZ/ibG6T+PxZ1LDpdZCQ8oeJJrXd4EE'
);

CREATE TABLE IF NOT EXISTS users(
  name VARCHAR(30) NOT NULL,
  mobNoEn VARBINARY(38) NOT NULL,
  mobNoHs VARBINARY(32) UNIQUE NOT NULL,
  type SMALLINT,
  actBy CHAR(8) REFERENCES admins(userId)
);

CREATE TABLE IF NOT EXISTS blocks(
  mobNoEc VARBINARY(38) NOT NULL,
  mobNoHs VARBINARY(32) UNIQUE NOT NULL,
  type SMALLINT,
  actBy CHAR(8) REFERENCES admins(userId)
);


CREATE TABLE IF NOT EXISTS reports(
  mobNoEc VARBINARY(38) NOT NULL,
  mobNoHs VARBINARY(32) UNIQUE NOT NULL,
  type SMALLINT,
  repBy VARBINARY(32) NOT NULL REFERENCES users(mobNoHS),
  actBy CHAR(8) REFERENCES admins(userId)
);