export const DB_PASS = process.env.DB_PASS;
export const DB_HOST = process.env.DB_HOST || "localhost";
export const DB_NAME = process.env.DB_NAME;
export const REDIS_HOST = process.env.REDIS_HOST || "localhost";
export const ENC_KEY = Buffer.from(process.env.ENC_KEY || "", "utf8");
export const HASH_KEY = process.env.HASH_KEY || "";
export const rpName = process.env.RP_NAME || "scb";
export const rpID = process.env.RP_ID || "localhost";
export const rpPORT = process.env.RP_PORT || 3000;
