CREATE DATABASE IF NOT EXISTS SCB;

USE SCB;

CREATE TABLE IF NOT EXISTS departments(department VARCHAR(30) PRIMARY KEY);

CREATE TABLE IF NOT EXISTS reports(
  id SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  MNE VARCHAR(80) NOT NULL,
  RMNE VARCHAR(80) NOT NULL,
  stat TINYINT DEFAULT 1,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  blockedBy VARCHAR(50),
  FOREIGN KEY (blockedBy) REFERENCES admins(userId),
  FOREIGN KEY (RMNE) REFERENCES clients(MNE),
)