CREATE DATABASE IF NOT EXISTS SCB;

USE SCB;

CREATE TABLE IF NOT EXISTS blockedNo(
  id SMALLINT AUTO_INCREMENT PRIMARY KEY,
  mobileNoHashed VARCHAR(50) UNIQUE NOT NULL,
  mobileNoEncrypted VARCHAR(80) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);