CREATE DATABASE IF NOT EXISTS SCB;

USE SCB;

CREATE TABLE IF NOT EXISTS numbers(
  id SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  MNH VARCHAR(50) UNIQUE NOT NULL,
  MNE VARCHAR(80) NOT NULL,
  blockedBy VARCHAR(50) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (blockedBy) REFERENCES admins(userId)
);

CREATE TABLE IF NOT EXISTS numbers(
  id SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(50) UNIQUE NOT NULL,
  blockedBy VARCHAR(50) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (blockedBy) REFERENCES admins(userId)
);