CREATE DATABASE IF NOT EXISTS SCB;

USE SCB;

CREATE TABLE IF NOT EXISTS users (
  mobileNoHashed VARCHAR(50) PRIMARY KEY,
  mobileNoEncrypted VARCHAR(75) NOT NULL,
  username VARCHAR(30) NOT NULL,
  authenticated BOOLEAN DEFAULT 0,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sessions (
  token VARCHAR(250) NOT NULL,
  mobileNoHashed VARCHAR(50) PRIMARY KEY,
  CONSTRAINT fk_session_mobileNoHashed FOREIGN KEY (mobileNoHashed) REFERENCES users (mobileNoHashed) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS admins (
  userId VARCHAR(30) PRIMARY KEY,
  passwordHashed VARCHAR(100) NOT NULL,
  mobileNoHashed VARCHAR(50),
  role BOOLEAN DEFAULT 0,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_admin_mobileNoHashed FOREIGN KEY (mobileNoHashed) REFERENCES users (mobileNoHashed) ON DELETE CASCADE ON UPDATE CASCADE
);